  apiVersion: v1
  kind: LimitRange
  metadata:
    name: joaolobo-limitrange
    #namespace: demo
  spec:
    limits:
    - default:
        cpu: "500m"
        memory: "256Mi"
      defaultRequest:
        cpu: "200m"
        memory: 128Mi"
      type: COntainer
