apiVersion: apps/v1
kind: Deployment
namespace: {{ .Values.container.namespace }}
metadata:
  name: {{ .Values.container.name }}--{{ .Values.environment }}
  labels:
    app: {{ .Values.container.name }}
spec:
  replicas: {{ .Values.container.name }}
  selector:
    matchLabels:
      app: {{ .Values.container.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.container.name }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}:{{ .Values.container.tag }}
          ports:
          -  containerPort: {{ .Values.container.port }}
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment }}