apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.name }}-service-{{ .- if regexMatch "(?:[0-9]{1,3}\.){3}[0-9]{1,3}$"  }}
  namespace: {{ .Values.container.namespace }}{{ .Values.environment }}
  labels:
    app: {{ .Values.container.name }}
spec:
  ports:
  - port: {{ .Values.container.port }}
    protocol: TCP
    targetPort: {{ .Values.container.port }}
  selector:
    app: {{ .Values.container.name }}
  type: ClusterIP
