apiVersion: v1
kind: Service
namespace: joaolobo
metadata:
  name: joaolobo-dev
  labels:
    app: joaolobo-dev
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: joaolobo-dev
  type: ClusterIP
