apiVersion: v1
kind: Service
namespace: {{ .Values.container.namespace }}
metadata:
  name: {{ .Values.container.name }}-service-{{ .Values.container.environment }}
  labels:
    app: {{ .Values.container.name }}
spec:
  ports:
  - port: {{ .Values.container.port }}
    protocol: TCP
    targetPort: {{ .Values.container.port }}
  selector:
    app: {{ .Values.container.name }}
  type: ClusterIP
