apiVersion: v2
name: joaolobo-dev
description: A library chart with common helper functions userful for the joaolobo-dev application charts.
sources:
  - https://github.com/joaolgn1985/dev-test
version: 1.0.1
